---
abstract: 'store BLOBs in the file system'
author:
  - 'semifor: Marc Mims <marc@questright.com>'
build_requires:
  DBD::SQLite: 1.12
  DBICx::TestDatabase: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-InflateColumn-FS
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0.08
  DBIx::Class::UUIDColumns: 0.02005
  Path::Class: 0
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01003
